### PR TITLE
Rewrite grammar!

### PR DESCRIPTION
**Pull request by savq**
## Grammar

Rename "top-level" expressions:
- `SourceFile` to `Program`
- `ExpressionList` to `block`
- `AssignmentExpression` to `OpenAssignment` and `binding`
- `BareTupleExpression` to `OpenTuple`
- `e` to `expr`

Statements:
- Use `@extend` instead of `@specialize` for keywords
  - Allows quoting keywords like `:begin` and properties like `something.if.begin`
  - Allows `begin`/`end` identifiers without extra rules.
- Add separate rules for simple and compound (block) statements.

Definitions:
- Rename `Definition` to:
  - `TypeHead` for type definitions.
  - `Signature` for function and macro definitions.

Expressions:
- Add `operation` rule.
- Add `ClosedMacrocallExpression` and `OpenMacrocallExpression` as separate rules.
- Rename `FunctionExpression` to `ArrowFunctionExpression`
- Rename `CoefficientExpression` to `JuxtapositionExpression`
- Rename `TransposeExpression` to `AdjointExpression`
- Rename `SubscriptExpression` to `IndexExpression`

Tokens:
- Add rules for all mixed unary/binary operators.
- Add operator suffixes.
- Add `SyntacticOperator` rule.
- Add all numeric literals:
  - integers base 2, 8, 10 and 16
  - floats base 10 and 16 (with E notation)
- Add `EscapeSequence`.
- Use character sets for unicode operators.
- Replace external tokenizer for `BlockComment` with a skip rule.
  - Make nested `BlockComment` visible in the syntax tree.
- Replace external tokenizer for strings with skip rules.
  - Add non-standard string/command literal suffixes.
  - Add more command interpolations.
- Add `immediateIdentifier` external token for juxtapositions (instead
  of `nowhitespace`).
- Fix `x!=...` ambiguity (parse as `(!= x ...)`, not `(= x! ...)`)

Style and formatting:
- Rename rules to match Julia ASTs nomenclature as much as possible.
- Inline rules as much as possible.
- Use PascalCase for visible rules, and kebab-case for invisible ones.
- Use single quotes.

Node props:
- `@detectDelim` works by assigning a `closedBy` and `openedBy` props to the brackets themselves rather than the parent rule that contains them.

Regressions:

There's a small error when parsing function signatures: Return type annotations like `function f()::T` are parsed as `(signature (call f)) (:: T)` instead of `(signature (:: (call f) T))`.

## Tests
- Add `test/literals.txt`
- Add `test/primary.txt`
- Add `test/operators.txt`
- Add `test/collections.txt`
- Update `test/statements.txt`
- Update `test/definitions.txt`
- Update `test/expressions.txt`
- Move the tests in `test/edge-cases.txt`, `test/darl.txt`, and `test/dral2.txt` to related files.

## Parse script
- Add interactive mode
- Use `cursor.iterate` to simplify tree transversal
 
## Highlighting

- Add `src/highlight.js` file with highlighting information.

----

NOTES: 
- Since this is a complete rewrite the diff is rather useless. It's better to read the new files on their own.
- The new `bin/parse.js` script has an interactive "repl" mode. That's the easiest way to play around with the new grammar.
- Compilation time was significantly reduced, but it still takes a while (2-3 minutes) and still requires the `--max-old-space-size` hack.

### CODE REVIEW

**Comment by savq** [comment]
Here's how it looks so far compared to the current syntax highlighting (old on the left, new syntax on the right):

<a href="url"></a>

<a href="url"></a>

**Comment by savq** [comment]
I fixed the remaining issues with keywords-as-identifiers ([context](https://discuss.codemirror.net/t/context-sensitive-keywords-as-identifiers-looking-for-alternatives-to-extend/8277)), so the rewrite is now complete. For realsies.

**Comment by fonsp** [comment]
Wowww congrats @savq! I'm on my phone so no gif but here is a picture of a butterfly:

image

**Comment by savq** [comment]
@Pangoraw I fixed the parsing of anonymous functions, and added some basic highlighting for types.

I also updated the props used for indentation, which was the remaining task for the PR in lang-julia.

**Comment by fonsp** [comment]
Hey @savq ! Maybe this should be merged before it becomes too long ago! Can future changes be done in separate PRs?

**Comment by savq** [comment]
Yes, we can merge this now.

@fonsp could you publish the release to npm?

**Comment by fonsp** [comment]
Yes! What is your npm username? Then I will add you to the plutojl org

FYI the tests failed on two tests:

```

➜  lezer-julia git:(main) ✗ npm run test

> @plutojl/lezer-julia@0.12.0 test
> mocha test/test-*.js



  collections
    ✔ Tuples
    ✔ Named tuples
    ✔ Named tuples with leading semicolon
    ✔ Vector arrays
    ✔ Matrix arrays
    ✔ Field expressions - typed_ncat
    ✔ Comprehension arrays
    ✔ Generator expressions
    ✔ Generator expressions in function calls

  definitions
    ✔ Modules
    ✔ Abstract type definitions
    ✔ Primitive type definitions
    ✔ Struct definitions
    ✔ Mutable struct definitions
    ✔ Parametric struct definitions
    ✔ Parametric struct definitions with subtyping
    ✔ Parametric struct fields
    ✔ Function definitions
    ✔ Function definitions - Operators
    ✔ Function definitions - Callable structs
    ✔ function definitions - Zero method definitions
    ✔ Function definitions - Anonymous functions
    ✔ Function definitions - Anonymous functions with no parameters
    ✔ Function definitions - Return type annotations # FIXME
    ✔ Function definitions - Signature with `where` expression # FIXME
    ✔ Function definitions - Typed parameters
    ✔ Function definitions - Typed parameters with FieldExpression type
    ✔ Function definitions - optional parameters
    ✔ Function definitions - keyword parameters
    ✔ Function definitions - Anonymous function with keyword parameters # BROKEN
    ✔ Macro definitions

  expressions
    ✔ Assignments
    ✔ Assignments - Short functions
    ✔ Type declarations
    ✔ Arrow function expressions
    ✔ Juxtaposition expressions - Coefficients
    ✔ Juxtaposition expressions - Monomials # FIXME
    ✔ Juxtaposition expressions - Primary LHS
    ✔ Ternary operator

  literals
    ✔ Boolean literals
    ✔ Integer number literals
    ✔ Float number literals
    ✔ Character literals
    ✔ String literals
    ✔ String literals - Escape sequences
    ✔ String literals - Interpolations
    ✔ String literals - Triple quote delimiters
    ✔ Non-standard string literals
    ✔ Command string literals
    ✔ Comments

  macros
    ✔ Closed macro call expressions
    ✔ Open macro call expressions
    ✔ Qualified macro identifiers
    ✔ Open macro call expressions - Assignments and open tuple arguments
    ✔ Open macro call expressions - Arguments spanning multiple lines
    ✔ Open macro call expressions - Block arguments
    ✔ Closed macro call expressions - Do blocks
    ✔ Open vs closed macro calls
    ✔ Macro calls as parameters

  operators
    1) Unary operators
    2) Binary arithmetic operators
    ✔ Binary arithmetic operators - operations spanning multiple lines
    ✔ Operator broadcasting
    ✔ Operator suffixes
    ✔ Binary bitwise operators
    ✔ Binary arrow-like operators
    ✔ Binary ellipsis operators
    ✔ Colon quines
    ✔ Binary comparison operators
    ✔ binary comparison operators - Types
    ✔ Operators as values
    ✔ Operators as values - function and macro names

  primary
    ✔ Identifiers
    ✔ Keywords as identifiers - Valid variable names
    ✔ Field expressions
    ✔ Keywords as identifiers - keywords as field names
    ✔ Index expressions
    ✔ Keywords as identifiers - begin/end indexing
    ✔ Type parametrized expressions
    ✔ Function call expressions
    ✔ Function call expressions - Broadcasting
    ✔ Function call expressions - Keyword arguments
    ✔ Function call expressions with do blocks
    ✔ Function call expressions with do blocks - no parameters
    ✔ Function call expressions with do blocks - typed parameter
    ✔ Quote expressions and symbols
    ✔ Keywords as identifiers - Quoted keywords
    ✔ Interpolation expressions
    ✔ Interpolation expressions - Interpolation in hcat # BROKEN
    ✔ Adjoint expressions

  statements
    ✔ Begin statements
    ✔ Quote statements
    ✔ While statements
    ✔ Let statements
    ✔ Let statements - No bindings
    ✔ For statements
    ✔ For outer statements
    ✔ If statements
    ✔ Try statements
    ✔ Return statements
    ✔ Export statements
    ✔ Export statements - Macro identifiers
    ✔ Import statements
    ✔ Import statements - Import aliases
    ✔ Const statements
    ✔ Local statements
    ✔ Global statements


  105 passing (46ms)
  2 failing

  1) operators
       Unary operators:
     Error: Expected end of UnaryExpression, got LineComment at 38 
Program(UnaryExpression(Identifier),UnaryExpression(Identifier),UnaryExpression(IntegerLiteral),UnaryExpression(AdjointExpression(Identifier),LineComment),BinaryExpression(UnaryExpression(Identifier),UnaryExpression(ParenExpression("(",Identifier,")"))),LineComment,BinaryExpression(IntegerLiteral,UnaryExpression(IntegerLiteral)))
      at enter (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/generator/dist/test.js:130:23)
      at Tree.iterate (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/common/dist/index.js:485:81)
      at testTree (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/generator/dist/test.js:109:10)
      at run (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/generator/dist/test.js:174:17)
      at Context.<anonymous> (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/test/test-julia.js:20:22)
      at process.processImmediate (node:internal/timers:483:21)

  2) operators
       Binary arithmetic operators:
     Error: Expected end of BinaryExpression, got LineComment at 39 
Program(BinaryExpression(Identifier,IntegerLiteral),UnaryExpression(BinaryExpression(Identifier,IntegerLiteral,LineComment)),BinaryExpression(Identifier,Identifier),BinaryExpression(Identifier,Identifier),BinaryExpression(Identifier,BinaryExpression(IntegerLiteral,BinaryExpression(Identifier,IntegerLiteral))),LineComment,BinaryExpression(Identifier,ParenExpression("(",BinaryExpression(Identifier,Identifier),")")))
      at enter (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/generator/dist/test.js:130:23)
      at Tree.iterate (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/common/dist/index.js:485:81)
      at testTree (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/generator/dist/test.js:109:10)
      at run (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/node_modules/@lezer/generator/dist/test.js:174:17)
      at Context.<anonymous> (file:///Users/fons/Documents/local-codemirror-pluto-setup-thing/packages/lezer-julia/test/test-julia.js:20:22)
      at process.processImmediate (node:internal/timers:483:21)



```

**Comment by fonsp** [comment]
https://www.npmjs.com/package/@plutojl/lezer-julia/v/0.12.0

**Comment by fonsp** [comment]
I tried but this didnt work

Scherm­afbeelding 2024-08-06 om 09 32 08

**Comment by savq** [comment]
Weird. I didn't have that issue, but it did show up when I did a fresh install. It was probably a dependency version error on my part.

The newer version is technically correct (the best kind of correct), since the comment is before the line break, it's part of the expression, not something between expressions.

**Pull request merged**
